apiVersion: v1
kind: Deployment
metadata:
 name: hello-world
 labels:
   app: web
spec:
  containers:
    - name: hello-world-cont
      image: registrypoc.azurecr.io/registrypoc/hello-world
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: registrykey
