apiVersion: v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: registrypoc.azurecr.io/registrypoc/hello-world
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: registrykey
