apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nghw-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
      - name: hello-world
        image: registrypoc.azurecr.io/hello-world
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: nghw-service
  labels:
    run: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: hello-world
