apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nghw-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
      - name: hello-world
        image: registrypoc.azurecr.io/registrypoc/hello-world
        ports:
        - containerPort: 80
